version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./app:/app/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: